name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms and build-tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"

      - name: Cache Kotlin/Native (konan)
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', 'gradle/libs.versions.toml') }}

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Assemble Android Debug
        run: ./gradlew :composeApp:assembleDebug --stacktrace

      - name: Run checks
        run: ./gradlew :composeApp:check --stacktrace

